matrix: 
  include: 

    # Build for Angular (front-end)
    - language: node_js
      node_js:
        - "9"
      dist: trusty
      sudo: required

      branches:
        only:
          - master

      before_script:
        - npm install -g @angular/cli

      script:
        - ng build --prod
        - ng lint
        - ng test
		 